version: '3.8'

services:
  api:
    build: .
    image: hasan/chat/api/1
    restart: "no"
    environment:
      DB_URI: "postgres://postgres:password@postgresql:5432/hasan-node-postgres-1"
    ports:
      - 2312:2312
      - 7424:7424

  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_DATABASE: chat_redis_socket
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  mongodb:
  mongodb_config:
